name: Deploy - PROD

on:
  push:
    branches:
      - master

jobs:
  Setup:
    runs-on: ubuntu-latest

    steps:
      - name: Get repository source
        uses: actions/checkout@v3

  BuildAndPushImageToECR:
    runs-on: ubuntu-latest

    steps:
      - name: Get repository source
        uses: actions/checkout@v3

      - run: docker build --tag rango-app .
      - name: Push to ECR
        uses: jwalton/gh-ecr-push@v1
        with:
          access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          region: us-east-1
          image: rango-app
